INSERT INTO "cuentas_contables" ("code", "name", "type", "nature", "description", "isActive")
VALUES
  ('1', 'ACTIVOS', 'ACTIVO', 'DEBITORA', 'Cuentas de activo general', true),
  ('1.1', 'Caja Principal', 'ACTIVO', 'DEBITORA', 'Dinero en oficina y bancos', true),
  ('1.1.1', 'Caja Oficina Central', 'ACTIVO', 'DEBITORA', 'Efectivo fisico en oficina', true),
  ('1.1.2', 'Cuentas Bancarias', 'ACTIVO', 'DEBITORA', 'Dinero en bancos y billeteras', true),
  ('1.2', 'Cajas de Ruta', 'ACTIVO', 'DEBITORA', 'Efectivo en poder de cobradores', true),
  ('1.2.1', 'Caja Ruta General', 'ACTIVO', 'DEBITORA', 'Cuenta control para billeteras de cobradores', true),
  ('1.2.1.E', 'Caja Ruta - Efectivo', 'ACTIVO', 'DEBITORA', 'Recaudo en efectivo por cobrador', true),
  ('1.2.1.T', 'Caja Ruta - Transferencia', 'ACTIVO', 'DEBITORA', 'Recaudo por transferencia pendiente de conciliacion', true),
  ('1.3', 'Cartera de Prestamos', 'ACTIVO', 'DEBITORA', 'Derechos de cobro sobre clientes', true),
  ('1.3.1', 'Cartera Vigente', 'ACTIVO', 'DEBITORA', 'Prestamos en estado activo', true),
  ('1.3.2', 'Cartera en Mora', 'ACTIVO', 'DEBITORA', 'Prestamos con cuotas vencidas', true),
  ('1.4', 'Cuentas Cobrar Cobradores', 'ACTIVO', 'DEBITORA', 'Deudas de empleados por descuadres o adelantos', true),
  ('1.4.1', 'Deuda Cobrador General', 'ACTIVO', 'DEBITORA', 'Subcuenta de control de deudas', true),
  ('2', 'PATRIMONIO Y PASIVOS', 'PATRIMONIO', 'ACREEDORA', 'Obligaciones y capital', true),
  ('2.1', 'Capital del Propietario', 'PATRIMONIO', 'ACREEDORA', 'Inversion inicial del dueno', true),
  ('2.2', 'Utilidades Retenidas', 'PATRIMONIO', 'ACREEDORA', 'Ganancias de ejercicios anteriores', true),
  ('2.3', 'Utilidad del Periodo', 'PATRIMONIO', 'ACREEDORA', 'Ganancia neta calculada', true),
  ('2.4', 'Ajustes Pendientes', 'PASIVO', 'ACREEDORA', 'Sobrantes de arqueo por identificar', true),
  ('3', 'INGRESOS', 'INGRESOS', 'ACREEDORA', 'Aumentos en el patrimonio por actividad', true),
  ('3.1', 'Ingresos por Intereses', 'INGRESOS', 'ACREEDORA', 'Interes corriente de prestamos', true),
  ('3.2', 'Ingresos por Mora', 'INGRESOS', 'ACREEDORA', 'Interes por mora y penalidades', true),
  ('3.3', 'Otros Ingresos Oper.', 'INGRESOS', 'ACREEDORA', 'Margen de articulos u otros conceptos', true),
  ('4', 'GASTOS', 'GASTOS', 'DEBITORA', 'Disminuciones en el patrimonio por operacion', true),
  ('4.1', 'Gastos de Ruta', 'GASTOS', 'DEBITORA', 'Gasolina, papeleria y viaticos', true),
  ('4.2', 'Gastos Administrativos', 'GASTOS', 'DEBITORA', 'Nomina, servicios y arriendos', true),
  ('4.3', 'Perdidas Incobrables', 'GASTOS', 'DEBITORA', 'Condonaciones o prestamos perdidos', true)
ON CONFLICT ("code") DO UPDATE SET
  "name" = EXCLUDED."name",
  "type" = EXCLUDED."type",
  "nature" = EXCLUDED."nature",
  "description" = EXCLUDED."description",
  "isActive" = true;
